/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.epoo;
import static com.mycompany.epoo.Estruturas.cargaCaminhao;
import static com.mycompany.epoo.Estruturas.stock;
import static com.mycompany.epoo.Transportadora.valorKm;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/** 
 * 
 * @author Katherin
 */
public class FrameTransportadora extends javax.swing.JFrame {

    
    public static final String PATH_Caminhao = "c:/tmp/Caminhao.csv"; 
    public static final String PATH_Cargas = "c:/tmp/CargasRecebidas.csv"; 
     public static final String PATH_Historial = "c:/tmp/Historial.csv";
    
    Arquivos arq = new Arquivos();
    /**
     * Creates new form FrameTransportadora
     */
     
   
    TransportadoraTM Modelo; 

    public FrameTransportadora() {
      
        initComponents();
        
        Modelo=new TransportadoraTM(Arquivos.Ler(PATH_Cargas));//esse comenado e para atualizar a tabela carregando os dados assim que iniciada
  
        tbl_cargas.setModel(Modelo); // eu aqui estou setando o tipo de tabela, ou seja o modelo que vai seguir

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jPanel3 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        txt_nome = new java.awt.TextField();
        txt_destinatario = new java.awt.TextField();
        cb_Cidade = new javax.swing.JComboBox<>();
        btn_cadastrar = new java.awt.Button();
        btn_fechar = new java.awt.Button();
        txt_alt = new java.awt.TextField();
        txt_lar = new java.awt.TextField();
        txt_comp = new java.awt.TextField();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cargas = new javax.swing.JTable();
        btn_carrega = new java.awt.Button();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 102));

        label1.setFont(new java.awt.Font("Gentium Book Basic", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setName(""); // NOI18N
        label1.setText("TRANSPORTADORA E-POO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do cliente"));

        label2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        label2.setText("Nome Remetente:");

        label3.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        label3.setText("Destinatario:");

        label4.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        label4.setText("Cidade destino:");

        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });

        txt_destinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_destinatarioActionPerformed(evt);
            }
        });

        cb_Cidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bage", "Pelotas", "Rio Grande" }));
        cb_Cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_CidadeActionPerformed(evt);
            }
        });

        btn_cadastrar.setLabel("Cadastrar");
        btn_cadastrar.setName(""); // NOI18N
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_fechar.setLabel("Fechar carga ");
        btn_fechar.setName(""); // NOI18N
        btn_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fecharActionPerformed(evt);
            }
        });

        txt_alt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_altActionPerformed(evt);
            }
        });

        txt_lar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_larActionPerformed(evt);
            }
        });

        txt_comp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_compActionPerformed(evt);
            }
        });

        label6.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        label6.setText("Largura");

        label7.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        label7.setText("Altura");

        label8.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        label8.setText("Comprimento");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_alt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(txt_lar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)
                                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_comp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cb_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_destinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_destinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_alt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_comp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btn_fechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tbl_cargas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl_cargas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Remetente", "Destinatario", "Volume de carga", "Distancia em KM", "Valor total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_cargas);

        btn_carrega.setLabel("Carregar ");
        btn_carrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carregaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_carrega, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_carrega, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_destinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_destinatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_destinatarioActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
       
        
      
        float x=0, volume=0;
        try{
        volume=(Float.parseFloat(txt_lar.getText())*Float.parseFloat(txt_alt.getText())*Float.parseFloat(txt_comp.getText()));
     
        }catch(Exception e){
            e.getMessage();
            txt_lar.setBackground(Color.red);
             txt_alt.setBackground(Color.red);
              txt_comp.setBackground(Color.red);
              JOptionPane.showMessageDialog(null, "Porfavor preencha todos os campos com os valores correspondentes, numeros devem ser inteiros ou seguidos por ponto!");
        }
        switch(cb_Cidade.getSelectedIndex()){
            //bage - pelotas - rio grande
            case 0: //bage
                   x= 180;
                   break;
            case 1://pelotas
                   x=340;
                break;
                
            case 2://rio grande
                   x=400;
                break;
        }
           if(volume==0){
            JOptionPane.showMessageDialog(null, "Os valores da cubagem nao podem ser zero!");
        }else{
        
         try{
        if(volume<=50 ){
       String nome= txt_nome.getText();
       String nomeDes=txt_destinatario.getText();
       float vol=volume;
       float distancia= x;
       double valorCarga=(valorKm*x*volume);
       
       if((txt_nome.getText().isEmpty()) && (txt_destinatario.getText().isEmpty())){
          JOptionPane.showMessageDialog(null, "Porfavor, preencha todos os campos!");
          txt_nome.setBackground(Color.CYAN);
          txt_destinatario.setBackground(Color.CYAN);
       }
       else{
            Transportadora t = new Transportadora(nome,nomeDes,vol,distancia,valorCarga);
            Modelo.addTransportadora(t);
           }
        }
        else{
            JOptionPane.showMessageDialog(null, "O volume da carga não deve ultrapasar os 50m^3");
        }
        }
        catch(Exception e){
            e.getStackTrace();
            JOptionPane.showMessageDialog(null,"Erro ao inserir dados. Porfavor preencha todos os campos corretamente");
        }
           
        try {
            Arquivos.EscritaCargas(Modelo.returnArray(), "c:/tmp/CargasRecebidas.csv");
           
        } catch (Exception ex) {
            Logger.getLogger(FrameTransportadora.class.getName()).log(Level.SEVERE, null, ex);
        }
           
           }
            
        txt_nome.setText("");
        txt_alt.setText("");
        txt_lar.setText("");
        txt_comp.setText("");
        txt_destinatario.setText("");
           
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed



    }//GEN-LAST:event_txt_nomeActionPerformed

    private void cb_CidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_CidadeActionPerformed
        
      
        
        
    }//GEN-LAST:event_cb_CidadeActionPerformed

    private void txt_altActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_altActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_altActionPerformed

    private void txt_larActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_larActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_larActionPerformed

    private void txt_compActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_compActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_compActionPerformed

    private void btn_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fecharActionPerformed
//deve de ler os registros do arrayList, e ir acrecentando ao caminhao.csv enquanto o volume total seja<= 50

int resposta =JOptionPane.showConfirmDialog(null, "Deseja fechar a carga? Depois so podera fazer otra quando etregue as encomendas!", "Tem certeza?", JOptionPane.YES_NO_OPTION);
if (resposta == JOptionPane.YES_OPTION) {
    
    if(Modelo.returnArray().isEmpty()){
        JOptionPane.showMessageDialog(null, "Nao existem ainda registros para fechar a carga!");
    }else{
    if(cargaCaminhao.isEmpty()){
        
String registros="";
float volume=0;

   for(int i=0; i<Modelo.returnArray().size(); i++){
       
       Transportadora t= Modelo.returnArray().get(i);
        volume+=t.getVolumeCarga();
       
       if(volume<=50){
          registros+= "Cliente Destino: "+t.getNomeClienteDestino()+"\n "+ "\n "+
                  "Volume da carga: "+String.valueOf(t.getVolumeCarga())+
                  "\n "+ "\n "+"Distancia: "+String.valueOf(t.getDistancaoCidadeDestino()) + "\n "+ "\n "+
                 "Valor: R$"+ String.valueOf(t.getValorDaCarga())+ "\n" + "\n ";
         cargaCaminhao.add(t);
  
           }    else { 
                stock.add(t);
       }
 

       
    } //fin for
   
    //guardar ese registro en el csv caminhao
               //removerlo del array
        try {
            Arquivos.EscritaCargas(cargaCaminhao, PATH_Caminhao);
            
        } catch (IOException ex) {
            Logger.getLogger(FrameTransportadora.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, registros);
        Modelo.limpar();
        try {
            Arquivos.EscritaCargas(Modelo.returnArray(), PATH_Cargas); //esto hice para que quedara solo con los registros que aun no fueron cargados
            
        } catch (IOException ex) {
            Logger.getLogger(FrameTransportadora.class.getName()).log(Level.SEVERE, null, ex);
        }
        Modelo.addLista(stock);
        try {
            Arquivos.EscritaCargas(stock, PATH_Cargas);
            
        } catch (IOException ex) {
            Logger.getLogger(FrameTransportadora.class.getName()).log(Level.SEVERE, null, ex);
        }
        stock.clear();
    
    
    
    }else {
        JOptionPane.showMessageDialog(null, "Ja existe uma carga fechada!");
    }
    }
} else {
    JOptionPane.showMessageDialog(null, "Ok... Cancelando fechamento da carga");
    System.exit(0);
}
    }//GEN-LAST:event_btn_fecharActionPerformed

    private void btn_carregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carregaActionPerformed

        if(cargaCaminhao.isEmpty()){
            JOptionPane.showMessageDialog(null, "Para carregar o caminhao primeiro feche a carga!");
        }else{
        Estruturas.carregarCaminhao();
        
        Gerenciamento ger= new Gerenciamento();
        ger.setVisible(true);
            this.dispose();
        
        }
        

        
    }//GEN-LAST:event_btn_carregaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTransportadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTransportadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTransportadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTransportadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTransportadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_cadastrar;
    private java.awt.Button btn_carrega;
    private java.awt.Button btn_fechar;
    private javax.swing.JComboBox<String> cb_Cidade;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private javax.swing.JTable tbl_cargas;
    private java.awt.TextField txt_alt;
    private java.awt.TextField txt_comp;
    private java.awt.TextField txt_destinatario;
    private java.awt.TextField txt_lar;
    private java.awt.TextField txt_nome;
    // End of variables declaration//GEN-END:variables
}
